### PR TITLE
Added optimization flag to Makefile.def and fixed spelling error

### PR DESCRIPTION
**Pull request by nrg500**
I noticed ncompress was not using any optimization flags, I've tested on an aarch64 testbuild and my own x86_64 Fedora installation to see if the -O3 (Agressive optimization) had any side effects on the code, but my files still compressed and uncompressed like they should. I used md5sum to verify that both the uncompressed and compressed files did not change at all in comparison to the version without -O3. I cannot speak for any other architectures though since I don't have them available for testing. 

I've documented my process, benchmarks and findings here:
[http://berwoutcanada.blogspot.ca/](url)

There is a significant increase in speed with the optimization flag turned on.

### CODE REVIEW

**Comment by vapier** [comment]
optimization selection is left up to the user.  we explicitly do not want to force an option like this.  this way you can do:
````
$ export CFLAGS='-O2'
$ make
````

unfortunately, there isn't a portable make way to do this.  in GNU make we'd do:
````
CFLAGS ?= -O2
````

**Comment by nrg500** [comment]
Thx for the reply,
Is there any reason you leave the optimizations to the user? It seems to me like users with not too much understanding of compiler optimizations would benefit from a default base level of optimization, while it should not hurt any other users.

**Comment by vapier** [comment]
as i mentioned, there isn't a way to do this in [portable make](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html).  if you know of a way, let me know ;).

**Comment by nrg500** [comment]
I'm not entirely sure if this breaks the specification you listed above, but this seems to work:

In the GNUMakefile replace:

> sed \
> 		-e 's:options= :options= $$(CFLAGS) -DNOFUNCDEF -DUTIME_H $$(LDFLAGS) :' \
> 		Makefile.def > Makefile

By:

> ifeq ($(strip $(CFLAGS)),)
> 	sed \
> 		-e 's:options= :options= -O2 -DNOFUNCDEF -DUTIME_H $$(LDFLAGS) :' \
> 	Makefile.def > Makefile
> else
> 	sed \
> 		-e 's:options= :options= $$(CFLAGS) -DNOFUNCDEF -DUTIME_H $$(LDFLAGS) :' \
> 		Makefile.def > Makefile
> endif

and remove the second $CFLAGS from the options in the Makefile.def (since the sed results in placing it twice there).

This makes it so that if anyone exported their own CFLAGS those get used, otherwise -O2 is applied. It would probably be better to store the base optimizations somewhere in a variable and then to refer to that, but this is to get the idea across :).

Would something like this be an idea?

p.s. the comment won't let me format it properly, if you'd like to test with it I can create a new pull request.

**Comment by vapier** [comment]
i implemented default flags via GNUmakefile export in commit 86d4d62558fe3823e8e00ae514309706d3a39e58

i also ran a spellchecker across Makefile.def and caught a lot more typos in commit 86c05f9279f7de5ad094f276559056f4836bab0b

thanks for the ideas

**Pull request closed without merging**
